SEQ_LENGTH: 24
TEST_RATIO: 0.2

RNN_EPOCHS: 20
RNN_BATCH_SIZE: 32

LSTM_EPOCHS: 5
LSTM_BATCH_SIZE: 32

MAX_EVALS: 5

MODEL_NAME: "LSTM"

gcp_project_id: "energy-ops-access"
gcs_primary_folder: "energy-ops-bucket/primary/data"